---

- name: Shell | install zsh
  apt: pkg=zsh state=latest update_cache=yes

- name: Shell | install ohmyzsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/$user/.oh-my-zsh

- name: Shell | copy aliases
  copy: src=.zsh_aliases dest=/home/$user/ owner=$user

- name: Shell | copy zshrc
  copy: src=.zshrc dest=/home/$user/.zshrc owner=$user

- name: Shell | set zsh shell for $user
  user: name=$user shell=/bin/zsh
