---
- name: install python packages
  apt: pkg=$item state=installed
  with_items:
    - python
    - python3
    - python-dev
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg62
    - libjpeg62-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-dev
    - python-setuptools
    - python-pip
    - python-virtualenv
    - virtualenvwrapper
    - python-memcache

