---

- name: install version control software
  apt: pkg=$item state=latest update_cache=yes
  with_items:
  - git
  - mercurial
  - mercurial-common
  - subversion
  - subversion-tools
  - bzr

- name: copy git completion
  copy: src=.git-completion.sh dest=/home/$user/ owner=$user mode=0664

- name: copy git config
  template: src=.gitconfig dest=/home/$user/.gitconfig owner=$user

